### PR TITLE
In page nav improvements

### PR DESCRIPTION
**Pull request by aurel-l**
Changes in InPageNav to handle better navigation
 - Not using hashes anymore
 - Fixes browser back/forward button

See InPageNav example in storybook

### CODE REVIEW

**Comment by dlrice** [comment]
I'm seeing this when viewing the story in Chrome and so not able to test the behaviour:
```
Uncaught DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
    at http://localhost:6006/main.bedbf6507298ec5af98b.bundle.js:5166:20
    at commitHookEffectList (http://localhost:6006/vendors~main.bedbf6507298ec5af98b.bundle.js:134983:26)
    at commitPassiveHookEffects (http://localhost:6006/vendors~main.bedbf6507298ec5af98b.bundle.js:135017:11)
    at HTMLUnknownElement.callCallback (http://localhost:6006/vendors~main.bedbf6507298ec5af98b.bundle.js:113289:14)
    at Object.invokeGuardedCallbackDev (http://localhost:6006/vendors~main.bedbf6507298ec5af98b.bundle.js:113338:16)
    at invokeGuardedCallback (http://localhost:6006/vendors~main.bedbf6507298ec5af98b.bundle.js:113393:31)
    at flushPassiveEffectsImpl (http://localhost:6006/vendors~main.bedbf6507298ec5af98b.bundle.js:138345:7)
    at unstable_runWithPriority (http://localhost:6006/vendors~main.bedbf6507298ec5af98b.bundle.js:172057:12)
    at runWithPriority$2 (http://localhost:6006/vendors~main.bedbf6507298ec5af98b.bundle.js:125102:10)
    at flushPassiveEffects (http://localhost:6006/vendors~main.bedbf6507298ec5af98b.bundle.js:138314:12)
```

**Comment by aurel-l** [comment]
> I'm seeing this when viewing the story in Chrome and so not able to test the behaviour:
> 
> ```
> Uncaught DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
>     at http://localhost:6006/main.bedbf6507298ec5af98b.bundle.js:5166:20
>     at commitHookEffectList (http://localhost:6006/vendors~main.bedbf6507298ec5af98b.bundle.js:134983:26)
>     at commitPassiveHookEffects (http://localhost:6006/vendors~main.bedbf6507298ec5af98b.bundle.js:135017:11)
>     at HTMLUnknownElement.callCallback (http://localhost:6006/vendors~main.bedbf6507298ec5af98b.bundle.js:113289:14)
>     at Object.invokeGuardedCallbackDev (http://localhost:6006/vendors~main.bedbf6507298ec5af98b.bundle.js:113338:16)
>     at invokeGuardedCallback (http://localhost:6006/vendors~main.bedbf6507298ec5af98b.bundle.js:113393:31)
>     at flushPassiveEffectsImpl (http://localhost:6006/vendors~main.bedbf6507298ec5af98b.bundle.js:138345:7)
>     at unstable_runWithPriority (http://localhost:6006/vendors~main.bedbf6507298ec5af98b.bundle.js:172057:12)
>     at runWithPriority$2 (http://localhost:6006/vendors~main.bedbf6507298ec5af98b.bundle.js:125102:10)
>     at flushPassiveEffects (http://localhost:6006/vendors~main.bedbf6507298ec5af98b.bundle.js:138314:12)
> ```

Oh, OK.
I know where this is coming from, but I thought that if animate was supported, partial keyframes would too. I'll check how to not use partial keyframes then

Just out of curiosity, which version of Chrome are you using? I'm on 81

**Comment by dlrice** [comment]
> Just out of curiosity, which version of Chrome are you using? I'm on 81

Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by aurel-l** [comment]
OK, strange, I can't seem to reproduce that error. I've pushed a change to not use partial keyframes (I believe). Could you have a try now please?

**Comment by dlrice** [comment]
Works!

**Review by dlrice — COMMENTED** [review]
Seeing an unexpected behavior which may just be something gone awry in the storybook rather than the in page nav component itself:

**Steps**
1. 	Click second link
2. 	Browser back
3. 	Browser forward

Expected to be at second link but still at first link

**Comment by aurel-l** [comment]
> Seeing an unexpected behavior which may just be something gone awry in the storybook rather than the in page nav component itself:
> 
> **Steps**
> 
>     1. Click second link
> 
>     2. Browser back
> 
>     3. Browser forward
> 
> 
> Expected to be at second link but still at first link

Good catch, I could reproduce it too. Not sure why this was happening, but waiting for the next frame to scroll solved it for me so I guess there was some race condition within the DOM interaction or something like that

**Review by dlrice — APPROVED** [review]

**Pull request merged**
